summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-11.0-x86_64/releases/download/2024.06.01/pkg-config-0.29.2-macos-11.0-x86_64.tar.xz
bin-sha: bf76992156cd08e1c27c608a274db88011136b3877787674dfd0c71fb1eb9ce6
